workflows:
  unity_ios:
    name: Unity iOS Build
    environment:
      xcode: latest
      cocoapods: default
      vars:
        UNITY_VERSION: ""   
    scripts:
      - name: Check Unity Versions
        script: |
          echo "📌 Listando versiones de Unity instaladas..."
          ls /Applications/Unity/Hub/Editor

      - name: Activate Unity License
        script: |
          echo "Activating Unity License"

      - name: Build iOS Player
        script: |
          /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity \
            -batchmode \
            -quit \
            -projectPath . \
            -buildTarget iOS \
            -executeMethod BuildScript.BuildIOS

    artifacts:
      - build/ios/**

    publishing:
      email:
        recipients:
          - "tu_correo@gmail.com"
